//Fetch container async API call actions
export const FETCH_CONTAINERS_REQUEST = 'FETCH_CONTAINERS_REQUEST'
export const FETCH_CONTAINERS_STARTED = 'FETCH_CONTAINERS_STARTED'
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS'
export const FETCH_CONTAINERS_FAILURE = 'FETCH_CONTAINERS_FAILURE'

//Start container async API call actions
export const START_CONTAINER_REQUEST = 'START_CONTAINER_REQUEST'
export const START_CONTAINERS_STARTED = 'START_CONTAINERS_STARTED'
export const START_CONTAINER_SUCCESS = 'START_CONTAINER_SUCCESS'
export const START_CONTAINER_FAILURE = 'START_CONTAINER_FAILURE'

//Start container async API call actions
export const STOP_CONTAINER_REQUEST = 'STOP_CONTAINER_REQUEST'
export const STOP_CONTAINER_SUCCESS = 'STOP_CONTAINER_SUCCESS'
export const STOP_CONTAINER_FAILURE = 'STOP_CONTAINER_FAILURE'

//Log actions
export const LOG_INFO = 'LOG_INFO'
export const LOG_WARN = 'LOG_WARN'
export const LOG_ERROR = 'LOG_ERROR'
export const LOG_CRITICAL = 'LOG_CRITICAL'

