//Fetch container async API call actions
export const FETCH_CONTAINERS_STARTED = 'FETCH_CONTAINERS_STARTED'
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS'
export const FETCH_CONTAINERS_FAILURE = 'FETCH_CONTAINERS_FAILURE'

//Fetch commands async API call actions
export const FETCH_COMMANDS_STARTED = 'FETCH_COMMANDS_STARTED'
export const FETCH_COMMANDS_SUCCESS = 'FETCH_COMMANDS_SUCCESS'
export const FETCH_COMMANDS_FAILURE = 'FETCH_COMMANDS_FAILURE'

//Build container async API call actions
export const BUILD_CONTAINER_STARTED = 'BUILD_CONTAINER_STARTED'
export const BUILD_CONTAINER_SUCCESS = 'BUILD_CONTAINER_SUCCESS'
export const BUILD_CONTAINER_FAILURE = 'BUILD_CONTAINER_FAILURE'

//Remove container async API call actions
export const REMOVE_CONTAINER_STARTED = 'REMOVE_CONTAINER_STARTED'
export const REMOVE_CONTAINER_SUCCESS = 'REMOVE_CONTAINER_SUCCESS'
export const REMOVE_CONTAINER_FAILURE = 'REMOVE_CONTAINER_FAILURE'

//Start container async API call actions
export const START_CONTAINER_STARTED = 'START_CONTAINER_STARTED'
export const START_CONTAINER_SUCCESS = 'START_CONTAINER_SUCCESS'
export const START_CONTAINER_FAILURE = 'START_CONTAINER_FAILURE'

//Stop container async API call actions
export const STOP_CONTAINER_STARTED = 'STOP_CONTAINER_STARTED'
export const STOP_CONTAINER_SUCCESS = 'STOP_CONTAINER_SUCCESS'
export const STOP_CONTAINER_FAILURE = 'STOP_CONTAINER_FAILURE'

//Log actions
export const LOG_INFO = 'LOG_INFO'
export const LOG_WARN = 'LOG_WARN'
export const LOG_ERROR = 'LOG_ERROR'
export const LOG_CRITICAL = 'LOG_CRITICAL'

